# Generated by Django 4.1.2 on 2022-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('pat_phone', models.CharField(max_length=10)),
                ('pat_email', models.EmailField(max_length=254)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
